using Microsoft.AspNetCore.Http;
using System;
using System.ComponentModel.DataAnnotations;

namespace ErJobPortal.Models
{
    public class TPORegistration
    {
        // =========================================================
        // BASIC DETAILS
        // =========================================================

        [Required(ErrorMessage = "Full Name is required.")]
        [StringLength(150)]
        public string FullName { get; set; }

        [Required(ErrorMessage = "College Email ID is required.")]
        [EmailAddress(ErrorMessage = "Enter a valid college email address.")]
        [StringLength(200)]
        public string CollegeMailID { get; set; }

        [Required(ErrorMessage = "Mobile Number is required.")]
        [Phone(ErrorMessage = "Enter a valid mobile number.")]
        [StringLength(15)]
        public string MobileNo { get; set; }


        // =========================================================
        // PASSWORD
        // =========================================================

        [Required(ErrorMessage = "Password is required.")]
        [StringLength(
            100,
            MinimumLength = 6,
            ErrorMessage = "Password must be at least 6 characters."
        )]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Confirm Password is required.")]
        [Compare(
            "Password",
            ErrorMessage = "Password and Confirm Password do not match."
        )]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }


        // =========================================================
        // COLLEGE / ORGANIZATION DETAILS
        // =========================================================

        [Required(ErrorMessage = "College Name is required.")]
        [StringLength(250)]
        public string CollegeName { get; set; }

        [StringLength(100)]
        public string CollegeCode { get; set; }

        [Required(ErrorMessage = "College Address is required.")]
        [StringLength(500)]
        public string CollegeAddress { get; set; }

        [StringLength(500)]
        [Url(ErrorMessage = "Enter a valid website URL.")]
        public string OrganizationWebsiteURL { get; set; }


        // =========================================================
        // EMPLOYEE / TPO DETAILS
        // =========================================================

        [Required(ErrorMessage = "Designation is required.")]
        [StringLength(150)]
        public string Designation { get; set; }

        [Required(ErrorMessage = "Department Name is required.")]
        [StringLength(150)]
        public string DepartmentName { get; set; }

        [Required(ErrorMessage = "College Employee ID is required.")]
        [StringLength(100)]
        public string CollegeEmployeeID { get; set; }


        // =========================================================
        // UPLOADED FILES
        // =========================================================

        public IFormFile SupportingDocument1File { get; set; }

        public IFormFile SupportingDocument2File { get; set; }

        public IFormFile ProfilePhotoFile { get; set; }


        // =========================================================
        // OTP
        // =========================================================

        public string OTP { get; set; }

        public string OTPType { get; set; }


        // =========================================================
        // DATABASE FILE PATHS
        // These are generated by the controller.
        // They are NOT form fields.
        // =========================================================

        public string? SupportingDocument1 { get; set; }

        public string? SupportingDocument2 { get; set; }

        public string? ProfilePhoto { get; set; }


        // =========================================================
        // APPROVAL / DATABASE FIELDS
        // These are managed by backend.
        // =========================================================

        public bool OTPVerified { get; set; }

        public string? Status { get; set; }

        public bool IsApproved { get; set; }

        public bool IsActive { get; set; }

        public int? ApprovedBy { get; set; }

        public DateTime? ApprovedDate { get; set; }

        public string? RejectionReason { get; set; }

        public DateTime? CreatedDate { get; set; }

        public DateTime? UpdatedDate { get; set; }
    }
}